### ISSUE TITLE
Can't do updates from DBeaver's UI

### ISSUE THREAD

**Issue by agolovenko** [aerospike/aerospike-jdbc#12]
I get this "Not implemented" error. The installed JDBC driver is the latest: `1.5.0`. 

As per docs such update queries are implemented. Am I missing something here? 

Thanks!

![Screen Shot 2022-05-12 at 12 52 55](https://user-images.githubusercontent.com/1433977/168055092-10c266ab-4b2c-4b80-bc65-8dc938e4bde2.png)

**Comment by reugn** [comment]
Hi @agolovenko, thanks for reporting this. There is work in progress on the next release which should address this issue.

**Comment by reugn** [comment]
@agolovenko, version 1.6.0 has been released.

**Comment by agolovenko** [comment]
@reugn I tried the new driver 1.6.0, and the error is now changed:
![Screen Shot 2022-05-18 at 14 56 42](https://user-images.githubusercontent.com/1433977/169043751-b460b21e-7f50-4ad1-8917-b6de93f91f49.png)

Please consider reopening this issue
