### ISSUE TITLE
Can aeropike version 4.3.1.5 be supported

### ISSUE THREAD

**Issue by zhbdesign** [aerospike/aerospike-jdbc#14]
Can aeropike version 4.3.1.5 be supported

**Comment by kportertx** [comment]
It will probably work, if not, try a release from when [4.3.1.latest](https://download.aerospike.com/download/server/notes.html#4.3.1.5) was new. 

But why are you on a 4 year old version of the server? You should at least upgrade to the latest hotfix version of that lineage. But hotfix releases typically stop after a year after the initial release of the subsequent lineage ([4.4.x](https://download.aerospike.com/download/server/notes.html#4.4.0.4)) - which was over 3 years ago.
