### ISSUE TITLE
Using DBeaver with sendKey=true but not getting keys in queries

### ISSUE THREAD

**Issue by miande-acxiom** [aerospike/aerospike-jdbc#17]
Using DBeaver: 22.2.4

Aerospike JDBC: 1.7.0

JDBC Connection String (IP was removed):
jdbc:aerospike:X.X.X.X:3000/test?sendKey=true

Using query:
SELECT * FROM test;

When viewing the results from the query the "__key" fields are "[NULL]".

**Comment by reugn** [comment]
@miande-acxiom make sure the records were written to the database with the `sendKey` policy set to true.

**Comment by miande-acxiom** [comment]
The records were uploaded to Aerospike using Aerospike's loader.

**Comment by reugn** [comment]
https://docs.aerospike.com/tools/asloader/options
See the `-uk` flag.

**Comment by miande-acxiom** [comment]
This resolved my issue.  Thank you, for your quick response to my questions and your clarity on how to resolve.
