### ISSUE TITLE
JDBI Bind variables are not supported.

### ISSUE THREAD

**Issue by KKDad** [aerospike/aerospike-jdbc#2]
Jdbi is built on top of JDBC and given the Aerospike JDBC driver, I would expect to be able to perform simple Jdbi queries with it. 

Following the https://jdbi.org/#_fluent_api, a simple queries such as the following should be expected to work:
~~~
 handle.createUpdate("INSERT INTO test.foo (PK, k1, k2, k3) VALUES (:id, :v1, :v2, v3)")
            .bind("id", 2)
            .bind("v1", "Apple")
            .bind("v2", "Banana")
            .bind("v3", "Cherry")
            .execute();
~~~

In reality, we see the following error:
~~~
INFO: Fetching SchemaTableName: com.aerospike.jdbc.model.SchemaTableName@693de35
Jun 02, 2021 11:13:50 AM com.aerospike.jdbc.AerospikeStatement executeQuery
INFO: executeQuery: INSERT INTO test.foo (PK, k1, k2, k3) VALUES (?, ?, ?, ?)

java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1

	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:373)
	at java.base/java.util.ArrayList.get(ArrayList.java:425)
~~~

This can be reproduced with a simple unit test.

**Comment by KKDad** [comment]
I've created 3 unit tests here to demonstrate the issue:
https://github.com/KKDad/aerospike-jdbc/commit/881152dab658c4acd1baf6b7b9564e2422c5de0e
The test `testJdbiInsertStringLiteral` passes, both `testJdbiBindVariablesPositions` and `testJdbiBindVariablesNames` are expected to pas, however they don't.

**Comment by reugn** [comment]
@KKDad, thanks for reporting. The fix will be released with the next driver version. Feel free to reopen if any related issue occurs.
