### ISSUE TITLE
services-alternate

### ISSUE THREAD

**Issue by Gaudeamus** [aerospike/aerospike-jdbc#6]
Hello, thanx for the driver

I wonder is there way to handle --services-alternate flag to have queries from cluster nodes with 
service.access-address - internal addresses
service.alternate-access-address - public addresses

**Comment by reugn** [comment]
@Gaudeamus I'm not sure I understand the question. Could you please refer to an example or any other project that implements this.

**Comment by kportertx** [comment]
@reugn, see https://javadoc.io/static/com.aerospike/aerospike-client/5.1.11/com/aerospike/client/policy/ClientPolicy.html#useServicesAlternate.

**Comment by Gaudeamus** [comment]
thank you @kportertx for directions
I've tried useServicesAlternate setting, but when I set connection url to 
`jdbc:aerospike:aerospike.distantcuster.net:3000/?useServicesAlternate=true`
I got error 
`Can not set boolean field com.aerospike.client.policy.ClientPolicy.useServicesAlternate to java.lang.String`

**Comment by reugn** [comment]
@Gaudeamus, the issue was addressed in v1.4.0. The version has been published to Maven Central and will be available in <24h.

**Comment by Gaudeamus** [comment]
thank you @reugn, for such quick response and fix
