### ISSUE TITLE
quoted sets names

### ISSUE THREAD

**Issue by Gaudeamus** [aerospike/aerospike-jdbc#8]
Hello, thanx for the driver!

Seems there is a problem working with quoted sets. And if set name is numeric, this is the only way the query could be made
For instance, I've made 2 queries, first using driver, second using aql 
```
insert into test."123" (__key,value) values (1,"value1")
```

```
aql> insert into test."321" (pk,value) values (1,"value1")
```

First query had made set `"123"` whilst second `321`, and I've not founded the way to select from `"123"`
```
aql> show sets
+------------------+----------------+------------------+---------+-------------------+---------+--------------+----------+-------------------+-------------------+--------------+------------+
| disable-eviction | ns             | index_populating | objects | stop-writes-count | set     | enable-index | sindexes | memory_data_bytes | device_data_bytes | truncate_lut | tombstones |
+------------------+----------------+------------------+---------+-------------------+---------+--------------+----------+-------------------+-------------------+--------------+------------+
| "false"          | "test"         | "false"          | "1"     | "0"               | ""123"" | "false"      | "0"      | "45"              | "80"              | "0"          | "0"        |
| "false"          | "test"         | "false"          | "1"     | "0"               | "321"   | "false"      | "0"      | "24"              | "64"              | "0"          | "0"        |
+------------------+----------------+------------------+---------+-------------------+---------+--------------+----------+-------------------+-------------------+--------------+------------+
```

After that I've tried to select data from correctly created `321` set. 
```
aql> select * from test."321" where pk=1
+----------+
| value    |
+----------+
| "value1" |
+----------+
```

Using driver, I get empty result quering with __key and selecting all 
```
select * from test."321" where __key=1
select * from test."321"

```

**Comment by Gaudeamus** [comment]
hello, can I do anything to clarify the issue?

**Comment by reugn** [comment]
Hi @Gaudeamus, the issue is clear. The [documentation](https://docs.aerospike.com/guide/limitations) says:
> Names can include only Latin lowercase and uppercase letters with no diacritical marks (a-z, A-Z), digits 0-9, underscores (_), hyphens (-), and dollar signs ($). This naming guideline is not enforced; however, if you do not follow it, some Aerospike features and tools might not function properly.

Yet this is not the priority, but it's good to have quoted schema/table names supported in the JDBC driver. We'll update here once this is implemented and released.

**Comment by reugn** [comment]
@Gaudeamus, version 1.6.0 has been released and it supports quoted table names.
